name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js and cache dependencies (lock file in lab folder)
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: modules/04.continuous-test/lab-corrections/package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: cd modules/04.continuous-test/lab-corrections && npm ci

      # Build project (if applicable)
      - name: Build project
        run: cd modules/04.continuous-test/lab-corrections && npm run build --if-present

      # Run tests
      - name: Run tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: cd modules/04.continuous-test/lab-corrections && npm test
